### ISSUE TITLE
Add additional columns to gh2csv output file

### ISSUE THREAD

**Issue by b3rn4rd0s** [rcbops/gh2#8]
We have recently updated the Waffle workflow for the rpc-openstack and u-suk-dev repos. The old workflow was:

Backlog > Approved > Doing > Needs Review > Pending SHA Update > Done

The new workflow is:

Backlog > **Triage** > **Investigate** > Approved > Doing > **Needs Review (Ready)** > **Needs Review (Doing)** > **Backport (Ready)** > **Backport (Doing)** > **Documentation (Ready)** > **Documentation (Doing)** > Pending SHA Update > Done

We need the script to account for the new workflow steps (**bolded**). 

We also need to see if this is going to blow through our GitHub API limits.

Relates to #7

**Comment by b3rn4rd0s** [comment]
@sigmavirus24 or @git-harry If one of y'all have a chance to play with this, please do a trial run. I'm concerned we may be pushing the script beyond it's ability to work within GitHub API limits. If not, I'll have @mancdaz experiment with this potential update.

**Comment by git-harry** [comment]
@b3rnard0 - It looks like a number of the new labels haven't been used yet so I can't be sure everything is working. I didn't have any rate limit issues. If you find any problems let me know in the review.

**Comment by b3rn4rd0s** [comment]
I believe this is done.
